version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-pedidos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos
    ports:
      - "3308:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql